import { PRODUCTS } from './config.js';

const root = document.querySelector('#modalRoot');
const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const close = () => { root.innerHTML = ''; };
function searchModal(){root.innerHTML=`<div class="modal"><div class="modal-box search-box"><button class="close" data-feature-close>×</button><span class="eyebrow">KLYVEN SEARCH</span><h2>FIND YOUR PIECE.</h2><label class="search-input">SEARCH THE DROP<input id="productSearch" autofocus placeholder="Try oversized tee"></label><div id="searchResults" class="search-results"></div></div></div>`;document.querySelector('#productSearch').focus();}
function accountModal(){root.innerHTML=`<div class="modal"><div class="modal-box"><button class="close" data-feature-close>×</button><span class="eyebrow">KLYVEN ACCOUNT</span><h2>YOUR SPACE.</h2><p>Account sign-in, order history, saved addresses and verified reviews are ready for a secure authentication connection. This release does not collect or store passwords in the browser.</p><div class="notice">Connect Supabase/Auth0/Firebase or your backend before enabling customer accounts publicly.</div><a class="button" href="#track" data-feature-close>Track an order</a></div></div>`}
function checkoutModal(){const total=document.querySelector('.summary-row.total span:last-child')?.textContent||'—';root.innerHTML=`<div class="modal"><div class="modal-box"><button class="close" data-feature-close>×</button><span class="eyebrow">SECURE CHECKOUT / FRONTEND MVP</span><h2>YOUR DELIVERY.</h2><form id="releaseCheckout" class="form-grid"><label>FULL NAME<input required></label><label>EMAIL<input type="email" required></label><label>MOBILE NUMBER<input inputmode="numeric" pattern="[0-9]{10}" required></label><label>PIN CODE<input inputmode="numeric" pattern="[0-9]{6}" required></label><label class="full">ADDRESS<input required></label><label>CITY<input required></label><label>STATE<input required></label><div class="full"><strong>PAYMENT METHOD</strong><label class="payment-option"><input type="radio" name="payment" value="upi" checked> MANUAL UPI — payment verification required</label><label class="payment-option"><input type="radio" name="payment" value="cod"> CASH ON DELIVERY</label><div class="notice"><b>UPI ID: klyven@upi</b><br>Pay the exact total, then share only the UTR/reference ID. Never enter UPI PIN, OTP, CVV or bank password.</div></div><button class="button full">Place order — ${total}</button></form></div></div>`}
function results(query=''){const target=document.querySelector('#searchResults');if(!target)return;const matches=PRODUCTS.filter(p=>`${p.name} ${p.category} ${p.collection}`.toLowerCase().includes(query.toLowerCase()));target.innerHTML=matches.length?matches.map(p=>`<a class="search-result" href="#product/${p.slug}" data-feature-close><img src="${p.images[0]}" alt="${p.name}"><span><b>${p.name}</b><small>${p.category} · ${money(p.price)}</small></span><i>↗</i></a>`).join(''):'<p class="empty">No pieces found. Try another search.</p>'}
document.addEventListener('click',event=>{const button=event.target.closest('button,a');if(!button)return;if(button.id==='searchToggle')searchModal();if(button.dataset.account!==undefined)accountModal();if(button.dataset.featureClose!==undefined||button.dataset.modalclose!==undefined)close();if(button.dataset.close!==undefined)document.querySelector('#drawerRoot').innerHTML='';if(button.dataset.checkout!==undefined)checkoutModal();});
document.addEventListener('input',event=>{if(event.target.id==='productSearch')results(event.target.value)});
document.addEventListener('submit',event=>{if(event.target.id==='releaseCheckout'){event.preventDefault();root.innerHTML=`<div class="modal"><div class="modal-box"><button class="close" data-feature-close>×</button><span class="eyebrow">ORDER REQUEST CREATED</span><h2>PAYMENT VERIFICATION.</h2><p>Your frontend order request has been validated. A production backend must create the unique order ID, save it, and send confirmation only after payment or COD verification.</p><a class="button" href="#track" data-feature-close>Track an order</a></div></div>`}});
